TaskCfg            = "./taskcfg"
DB                 = "./storage.db"
WorkerService      = ":18889"
PauseInterval      = 5   #60秒pause一次
PauseTime          = 5    #pause持续60秒，60秒后resume
PauseBroadcastTime = 5     #每5秒广播一次pause值


[Log]
MaxLogfileSize  = 104857600 # 100mb
LogDir          = "log"
LogLevel        = "debug"
LogPrefix       = "sche"
EnableStdout    = true
MaxAge          = 14   #最大保留14天的日志
MaxBackups      = 10   #最多保留10个滚动日志	