TaskCfg       = "./taskcfg"
Storage       = "./storage.txt"
WorkerService = ":18889"

[Log]
MaxLogfileSize  = 104857600 # 100mb
LogDir          = "log"
LogLevel        = "debug"
LogPrefix       = "sche"
EnableStdout    = true
MaxAge          = 14   #最大保留14天的日志
MaxBackups      = 10   #最多保留10个滚动日志	